// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NyTimesData;

#nullable disable

namespace NyTimesData.Migrations
{
    [DbContext(typeof(NyTimesDBContext))]
    partial class NyTimesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NyTimesData.Entity.Multimedium", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("ResultId")
                        .HasColumnType("bigint");

                    b.Property<string>("caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("copyright")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("height")
                        .HasColumnType("int");

                    b.Property<string>("subtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("Multimedia");
                });

            modelBuilder.Entity("NyTimesData.Entity.Result", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("RootId")
                        .HasColumnType("bigint");

                    b.Property<string>("abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("byline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("des_facet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("geo_facet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kicker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("material_type_facet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("org_facet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_facet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("published_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("short_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subsection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("uri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RootId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("NyTimesData.Entity.Root", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("copyright")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("last_updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("num_results")
                        .HasColumnType("int");

                    b.Property<string>("section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roots");
                });

            modelBuilder.Entity("NyTimesData.Entity.Multimedium", b =>
                {
                    b.HasOne("NyTimesData.Entity.Result", "result")
                        .WithMany("multimedia")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("result");
                });

            modelBuilder.Entity("NyTimesData.Entity.Result", b =>
                {
                    b.HasOne("NyTimesData.Entity.Root", "root")
                        .WithMany("results")
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("root");
                });

            modelBuilder.Entity("NyTimesData.Entity.Result", b =>
                {
                    b.Navigation("multimedia");
                });

            modelBuilder.Entity("NyTimesData.Entity.Root", b =>
                {
                    b.Navigation("results");
                });
#pragma warning restore 612, 618
        }
    }
}
